title: Tatrzańskie2k
description: Strona stanowi zwięzłą bazę informacji o położeniu oraz dostępnych drogach prowadzących na szczyty i przełęcze ujęte w projekcie Tatrzańskie Dwutysięczniki. Nie zawiera szczegółowych opisów tras, lecz opiera się przede wszystkim na mapach, które stanowią główne źródło informacji dla turystów.

theme: minima
# remote_theme: "jekyll/minima@b3385fe"
lang: pl
show_excerpts: false

minima:
  date_format: "%d.%m.%Y"
